receipts:
  - name: "Jane's I-485 (PR Application)"
    number: "LIN1111111186"
    emails: "jane.doe@example.com"
  - name: "Jane's I-765 (Employment Authorization)"
    number: "LIN1111111187"
    emails: "jane.doe@example.com"
  - name: "Jane's I-131 (Travel Document)`"
    number: "LIN1111111188"
    emails: "jane.doe@example.com"
  - name: "Jack's I-485 (PR Application)"
    number: "LIN1111111189"
    emails: "john.doe@example.com"
  - name: "Jack's I-131 (Travel Document)"
    number: "LIN1111111167"
    emails: "john.doe@example.com"
  - name: "Jack's I-765 (Employment Authorization)"
    number: "LIN1111111168"
    emails: "john.doe@example.com"
  - name: "Interfile"
    number: "MSC1111111142"
    emails: "jane.doe@example.com, john.doe@example.com"
